Expand README.

diff --git a/bin/autoscript b/bin/autoscript
--- a/bin/autoscript
+++ b/bin/autoscript
@@ -30,7 +30,7 @@ function ensure_storage_dir() {
 }
 
 function print_usage() {
-    printf "Usage: autoscript [-v] [-h] <command> [-i <id>]\n\n"
+    printf "usage: autoscript [-v] [-h] <command> [-i <id>]\n\n"
     printf "Available commands:\n"
     printf "   record\n"
     printf "   replay\n"
@@ -278,7 +278,7 @@ function main() {
         ;;
         resume)
             if [[ -n "$AUTOSCRIPT_ID" ]]; then
-                echo "Can't resume: you are currently inside an autoscript session." >&2
+                echo "Can't resume: you are already inside an autoscript session." >&2
                 exit 1
             fi
 
